import type { NextPage } from 'next'
import Head from 'next/head'

import { Header } from '../components/header/index';
import { Main } from '../components/main/index';
import { Footer } from '../components/footer/index';

const Home: NextPage = () => {
  return (
    <div className='home'>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header/>
      <Main/>
      <Footer/>

    </div>
  )
}

export default Home;
